import type { Stone } from "./stones";

/**
 * Real lab-grown stock, supplied by the trade desk (Surat). Report numbers are
 * intentionally left out of this file — they ship in the client bundle like
 * everything else here, and the site's design promises those only "on
 * enquiry", not to every visitor.
 *
 * `shape` groups stones by outline for filtering and the 3D wireframe;
 * `shapeName` keeps the supplier's own cut name for display. The two diverge
 * for a few real cuts with no dedicated shape of their own: "Octagonal" (an
 * eight-sided mixed cut) files under "asscher", whose outline is already
 * described as reading like an octagon; "Portuguese Cut" and "Round Mixed
 * Cut" (both round outlines with extra facet rows) file under "round".
 *
 * `cut` is omitted for every stone here except literal round brilliants —
 * IGI issues an overall cut grade only for that shape, leaving it blank on
 * every fancy-shape report in this batch.
 *
 * `color` holds a D–J grade for colourless-scale stones, or the report's own
 * fancy-colour wording ("Fancy Vivid Blue") for stones graded on that scale
 * instead — the two are mutually exclusive, never both graded on one report.
 * `isColorGrade()` in stones.ts tells the two apart wherever code needs to
 * (filtering, sorting) rather than guessing from the string's shape.
 *
 * Stock location (Surat or New York, on this supplier's reports) isn't
 * captured here either, for the same reason as the report number: it isn't
 * shown anywhere on the site, and there's no reason to ship it to every
 * visitor's browser.
 */
export const REAL_LAB_STONES: Stone[] = [
  {
    sku: "TP-280626-3329",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.5,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.22 x 7.24 x 4.53 mm",
    tablePercent: 59,
    depthPercent: 62.6,
    featured: false,
  },
  {
    sku: "TP-290526-3280",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.5,
    color: "E",
    clarity: "VS1",
    cut: "Very Good",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.26 x 7.29 x 4.62 mm",
    tablePercent: 55,
    depthPercent: 63.6,
    featured: false,
  },
  {
    sku: "TP-160625-1460",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.41,
    color: "F",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.23 x 7.25 x 4.41 mm",
    tablePercent: 59,
    depthPercent: 60.9,
    featured: false,
  },
  {
    sku: "TP-190425-1260",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.34,
    color: "E",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.02 x 7.04 x 4.37 mm",
    tablePercent: 59,
    depthPercent: 62.2,
    featured: false,
  },
  {
    sku: "TP-191225-2918",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.31,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.07 x 7.11 x 4.27 mm",
    tablePercent: 58,
    depthPercent: 60.3,
    featured: false,
  },
  {
    sku: "TP-190425-1258",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.3,
    color: "E",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.98 x 7 x 4.32 mm",
    tablePercent: 58,
    depthPercent: 61.8,
    featured: false,
  },
  {
    sku: "TP-130326-3154",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.23,
    color: "E",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.84 x 6.86 x 4.24 mm",
    tablePercent: 57,
    depthPercent: 61.9,
    featured: false,
  },
  {
    sku: "TP-191225-2919",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.22,
    color: "E",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.92 x 6.95 x 4.13 mm",
    tablePercent: 59,
    depthPercent: 59.6,
    featured: false,
  },
  {
    sku: "TP-060126-2953",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.2,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.76 x 6.78 x 4.24 mm",
    tablePercent: 58,
    depthPercent: 62.7,
    featured: false,
  },
  {
    sku: "TP-310126-3066",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.2,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.77 x 6.8 x 4.2 mm",
    tablePercent: 59,
    depthPercent: 61.9,
    featured: false,
  },
  {
    sku: "TP-150826-3372",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.09,
    color: "E",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.65 x 6.69 x 4.03 mm",
    tablePercent: 59,
    depthPercent: 60.4,
    featured: false,
  },
  {
    sku: "TP-150826-3370",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.05,
    color: "E",
    clarity: "VVS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.56 x 6.59 x 3.97 mm",
    tablePercent: 58,
    depthPercent: 60.5,
    featured: false,
  },
  {
    sku: "TP-150826-3371",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.01,
    color: "E",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.5 x 6.52 x 3.92 mm",
    tablePercent: 58,
    depthPercent: 60.2,
    featured: false,
  },
  {
    sku: "TP-030926-3381",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.01,
    color: "F",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.41 x 6.44 x 3.99 mm",
    tablePercent: 57,
    depthPercent: 62.2,
    featured: false,
  },
  {
    sku: "TP-030926-3384",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1,
    color: "E",
    clarity: "VS2",
    cut: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.31 x 6.35 x 4.01 mm",
    tablePercent: 56,
    depthPercent: 63.4,
    featured: false,
  },
  {
    sku: "TP-180526-3260",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1,
    color: "D",
    clarity: "VS1",
    cut: "Very Good",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.45 x 6.48 x 3.83 mm",
    tablePercent: 59,
    depthPercent: 59.2,
    featured: false,
  },
  {
    sku: "TP-100425-1221",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.96,
    color: "D",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.38 x 6.41 x 3.85 mm",
    tablePercent: 59,
    depthPercent: 60.3,
    featured: false,
  },
  {
    sku: "TP-160625-1473",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.91,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.18 x 6.2 x 3.84 mm",
    tablePercent: 58,
    depthPercent: 62,
    featured: false,
  },
  {
    sku: "TP-010425-1156",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.9,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.23 x 6.25 x 3.75 mm",
    tablePercent: 59,
    depthPercent: 60.1,
    featured: false,
  },
  {
    sku: "TP-220725-1984",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.79,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.83 x 5.89 x 3.67 mm",
    tablePercent: 61,
    depthPercent: 62.6,
    featured: false,
  },
  {
    sku: "TP-220725-1988",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.74,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.73 x 5.76 x 3.59 mm",
    tablePercent: 58,
    depthPercent: 62.5,
    featured: false,
  },
  {
    sku: "TP-191225-2923",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.74,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.79 x 5.84 x 3.56 mm",
    tablePercent: 63,
    depthPercent: 61.2,
    featured: false,
  },
  {
    sku: "TP-191225-2926",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.55,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.18 x 5.21 x 3.28 mm",
    tablePercent: 61,
    depthPercent: 63.1,
    featured: false,
  },
  {
    sku: "TP-220725-1991",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.52,
    color: "D",
    clarity: "VS1",
    cut: "Very Good",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.03 x 5.07 x 3.28 mm",
    tablePercent: 60,
    depthPercent: 64.9,
    featured: false,
  },
  {
    sku: "TP-220725-1993",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.51,
    color: "D",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.1 x 5.14 x 3.18 mm",
    tablePercent: 59,
    depthPercent: 62.1,
    featured: false,
  },


  // Cushion Brilliant
  {
    sku: "TP-020825-2075",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.51,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.41 x 6.35 x 4.20 mm",
    tablePercent: 64,
    depthPercent: 66.1,
    featured: false,
  },
  {
    sku: "TP-030725-1717",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.02,
    color: "D",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.75 x 5.76 x 3.54 mm",
    tablePercent: 64,
    depthPercent: 61.5,
    featured: false,
  },
  {
    sku: "TP-020825-2085",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.02,
    color: "D",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.61 x 5.47 x 3.91 mm",
    tablePercent: 68,
    depthPercent: 71.5,
    featured: false,
  },
  {
    sku: "TP-020825-2076",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 0.99,
    color: "D",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.73 x 5.65 x 3.76 mm",
    tablePercent: 58,
    depthPercent: 66.5,
    featured: false,
  },

  // Cushion Cut
  {
    sku: "TP-191225-2915",
    shape: "cushion",
    shapeName: "Cushion Cut",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.75,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.10 x 6.74 x 4.71 mm",
    tablePercent: 60,
    depthPercent: 69.9,
    featured: false,
  },

  // Emerald Cut
  {
    sku: "TP-250325-1119",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 2.77,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.33 x 6.73 x 4.51 mm",
    tablePercent: 64,
    depthPercent: 67,
    featured: false,
  },
  {
    sku: "TP-260526-3275",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 2.32,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.48 x 6.15 x 3.88 mm",
    tablePercent: 61,
    depthPercent: 63.1,
    featured: false,
  },
  {
    sku: "TP-070325-1029",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 2.25,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.23 x 5.97 x 4.00 mm",
    tablePercent: 67,
    depthPercent: 38.1,
    featured: false,
  },
  {
    sku: "TP-130526-3237",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 2.06,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.31 x 5.83 x 3.68 mm",
    tablePercent: 62,
    depthPercent: 63.1,
    featured: false,
  },
  {
    sku: "TP-150226-3108",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 2,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.02 x 5.87 x 3.71 mm",
    tablePercent: 65,
    depthPercent: 63.2,
    featured: false,
  },
  {
    sku: "TP-010325-998",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.53,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.62 x 5.45 x 3.64 mm",
    tablePercent: 64,
    depthPercent: 66.8,
    featured: false,
  },
  {
    sku: "TP-140326-3161",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.53,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.29 x 5.25 x 3.37 mm",
    tablePercent: 65,
    depthPercent: 64.2,
    featured: false,
  },

  // Heart Brilliant
  {
    sku: "TP-310526-3289",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 3.51,
    color: "F",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.98 x 9.79 x 5.99 mm",
    tablePercent: 58,
    depthPercent: 61.2,
    featured: false,
  },
  {
    sku: "TP-020626-3291",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.5,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.67 x 7.52 x 4.31 mm",
    tablePercent: 59,
    depthPercent: 57.3,
    featured: false,
  },
  {
    sku: "TP-220526-3269",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.89 x 6.47 x 4.34 mm",
    tablePercent: 58,
    depthPercent: 67.1,
    featured: false,
  },

  // Hexagonal Brilliant
  {
    sku: "TP-280626-3332",
    shape: "hexagon",
    shapeName: "Hexagonal Brilliant",
    shapeCode: "HX",
    origin: "lab",
    carat: 1.02,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.54 x 5.66 x 4.06 mm",
    tablePercent: 64,
    depthPercent: 71.7,
    featured: false,
  },
  {
    sku: "TP-280626-3333",
    shape: "hexagon",
    shapeName: "Hexagonal Brilliant",
    shapeCode: "HX",
    origin: "lab",
    carat: 1.02,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.38 x 5.71 x 3.90 mm",
    tablePercent: 68,
    depthPercent: 68.3,
    featured: false,
  },
  {
    sku: "TP-280626-3330",
    shape: "hexagon",
    shapeName: "Hexagonal Brilliant",
    shapeCode: "HX",
    origin: "lab",
    carat: 1.01,
    color: "F",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.55 x 5.65 x 3.88 mm",
    tablePercent: 70,
    depthPercent: 68.7,
    featured: false,
  },
  {
    sku: "TP-280626-3331",
    shape: "hexagon",
    shapeName: "Hexagonal Brilliant",
    shapeCode: "HX",
    origin: "lab",
    carat: 1.01,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.63 x 5.69 x 3.87 mm",
    tablePercent: 60,
    depthPercent: 68,
    featured: false,
  },
  {
    sku: "TP-250626-3329",
    shape: "hexagon",
    shapeName: "Hexagonal Brilliant",
    shapeCode: "HX",
    origin: "lab",
    carat: 0.92,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.41 x 5.50 x 3.78 mm",
    tablePercent: 65,
    depthPercent: 68.7,
    featured: false,
  },

  // Marquise Brilliant
  {
    sku: "TP-310525-1383",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 3.76,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "16.41 x 7.87 x 5.00 mm",
    tablePercent: 56,
    depthPercent: 63.5,
    featured: false,
  },
  {
    sku: "TP-080525-1318",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 2.99,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "15.65 x 7.27 x 4.63 mm",
    tablePercent: 59,
    depthPercent: 63.7,
    featured: false,
  },
  {
    sku: "TP-030926-3382",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 2.01,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "13.17 x 6.68 x 3.96 mm",
    tablePercent: 60,
    depthPercent: 59.3,
    featured: false,
  },
  {
    sku: "TP-150826-3373",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.53,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.45 x 6.08 x 3.73 mm",
    tablePercent: 59,
    depthPercent: 61.3,
    featured: false,
  },
  {
    sku: "TP-150826-3368",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.51,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "12.01 x 5.91 x 3.71 mm",
    tablePercent: 63,
    depthPercent: 62.8,
    featured: false,
  },
  {
    sku: "TP-180526-3261",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.51,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "13.12 x 5.83 x 3.53 mm",
    tablePercent: 58,
    depthPercent: 60.5,
    featured: false,
  },
  {
    sku: "TP-030726-3340",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.51,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.50 x 6.01 x 3.69 mm",
    tablePercent: 62,
    depthPercent: 61.4,
    featured: false,
  },
  {
    sku: "TP-020626-3292",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.51,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.88 x 5.88 x 3.74 mm",
    tablePercent: 60,
    depthPercent: 63.6,
    featured: false,
  },
  {
    sku: "TP-150826-3367",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.5,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "12.06 x 5.96 x 3.62 mm",
    tablePercent: 60,
    depthPercent: 60.7,
    featured: false,
  },
  {
    sku: "TP-150826-3369",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.5,
    color: "F",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.99 x 5.91 x 3.64 mm",
    tablePercent: 62,
    depthPercent: 61.6,
    featured: false,
  },
  {
    sku: "TP-290526-3278",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.5,
    color: "E",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.79 x 6.04 x 3.71 mm",
    tablePercent: 60,
    depthPercent: 61.4,
    featured: false,
  },
  {
    sku: "TP-150825-2164",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.35,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.45 x 5.70 x 3.58 mm",
    tablePercent: 58,
    depthPercent: 62.8,
    featured: false,
  },
  {
    sku: "TP-180526-3262",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.22,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.70 x 5.49 x 3.31 mm",
    tablePercent: 60,
    depthPercent: 60.3,
    featured: false,
  },
  {
    sku: "TP-240826-3376",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.14,
    color: "E",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.25 x 5.38 x 3.64 mm",
    tablePercent: 59,
    depthPercent: 67.7,
    featured: false,
  },
  {
    sku: "TP-250626-3327",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1,
    color: "E",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.56 x 5.46 x 3.08 mm",
    tablePercent: 61,
    depthPercent: 56.4,
    featured: false,
  },
  {
    sku: "TP-130626-3306",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.23 x 5.19 x 3.23 mm",
    tablePercent: 57,
    depthPercent: 62.2,
    featured: false,
  },

  // Octagonal
  {
    sku: "TP-201025-2546",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.4,
    color: "F",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.69 x 6.72 x 4.55 mm",
    tablePercent: 60,
    depthPercent: 67.7,
    featured: false,
  },
  {
    sku: "TP-220425-1279",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.2,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.29 x 6.81 x 4.31 mm",
    tablePercent: 58,
    depthPercent: 65,
    featured: false,
  },
  {
    sku: "TP-200625-1582",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.17,
    color: "F",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.79 x 6.77 x 4.20 mm",
    tablePercent: 54,
    depthPercent: 62,
    featured: false,
  },
  {
    sku: "TP-200625-1583",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.05,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.41 x 6.42 x 4.19 mm",
    tablePercent: 57,
    depthPercent: 65.3,
    featured: false,
  },
  {
    sku: "TP-190425-1261",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.03,
    color: "D",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.08 x 6.12 x 3.99 mm",
    tablePercent: 60,
    depthPercent: 65.4,
    featured: false,
  },
  {
    sku: "TP-130625-1386",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.03,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.01 x 6.52 x 4.01 mm",
    tablePercent: 58,
    depthPercent: 63.4,
    featured: false,
  },
  {
    sku: "TP-100126-3042",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.03,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.04 x 6.54 x 4.07 mm",
    tablePercent: 57,
    depthPercent: 63.9,
    featured: false,
  },
  {
    sku: "TP-200625-1605",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.03,
    color: "F",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.12 x 6.13 x 4.07 mm",
    tablePercent: 58,
    depthPercent: 66.4,
    featured: false,
  },
  {
    sku: "TP-210625-1605",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.02,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.05 x 6.16 x 4.03 mm",
    tablePercent: 62,
    depthPercent: 65.4,
    featured: false,
  },
  {
    sku: "TP-130625-1387",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.02,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.39 x 6.45 x 4.03 mm",
    tablePercent: 57,
    depthPercent: 62.5,
    featured: false,
  },
  {
    sku: "TP-200625-1612",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.01,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.05 x 6.06 x 4.05 mm",
    tablePercent: 65,
    depthPercent: 66.8,
    featured: false,
  },
  {
    sku: "TP-100126-3030",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.01,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.04 x 6.15 x 4.03 mm",
    tablePercent: 59,
    depthPercent: 66.1,
    featured: false,
  },
  {
    sku: "TP-220425-1280",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.01,
    color: "F",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.90 x 6.40 x 4.10 mm",
    tablePercent: 58,
    depthPercent: 65.9,
    featured: false,
  },
  {
    sku: "TP-200625-1609",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.01,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.06 x 6.09 x 4.02 mm",
    tablePercent: 62,
    depthPercent: 66,
    featured: false,
  },
  {
    sku: "TP-151025-2375",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.91 x 5.93 x 3.99 mm",
    tablePercent: 64,
    depthPercent: 67.3,
    featured: false,
  },
  {
    sku: "TP-040725-1840",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.90 x 6.40 x 4.04 mm",
    tablePercent: 60,
    depthPercent: 64.8,
    featured: false,
  },
  {
    sku: "TP-140326-3162",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.91 x 6.44 x 4.15 mm",
    tablePercent: 26,
    depthPercent: 32.2,
    featured: false,
  },
  {
    sku: "TP-030725-1714",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.96 x 5.84 x 4.04 mm",
    tablePercent: 66,
    depthPercent: 69.2,
    featured: false,
  },
  {
    sku: "TP-290325-1153",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 1,
    color: "D",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.94 x 5.96 x 4.05 mm",
    tablePercent: 59,
    depthPercent: 68,
    featured: false,
  },
  {
    sku: "TP-191225-2877",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 0.96,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.91 x 5.91 x 4.07 mm",
    tablePercent: 57,
    depthPercent: 68.9,
    featured: false,
  },
  {
    sku: "TP-110826-3366",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 0.94,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.54 x 6.51 x 3.84 mm",
    tablePercent: 57,
    depthPercent: 59,
    featured: false,
  },
  {
    sku: "TP-151025-2409",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 0.93,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.91 x 5.96 x 3.90 mm",
    tablePercent: 64,
    depthPercent: 65.4,
    featured: false,
  },
  {
    sku: "TP-11-1125-2736",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 0.92,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.96 x 5.95 x 3.80 mm",
    tablePercent: 59,
    depthPercent: 63.9,
    featured: false,
  },
  {
    sku: "TP-151025-2408",
    shape: "asscher",
    shapeName: "Octagonal",
    shapeCode: "AS",
    origin: "lab",
    carat: 0.92,
    color: "E",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.88 x 5.94 x 3.90 mm",
    tablePercent: 60,
    depthPercent: 65.7,
    featured: false,
  },

  // Oval Brilliant
  {
    sku: "TP-180325-1057",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.52,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.23 x 6.54 x 4.06 mm",
    tablePercent: 59,
    depthPercent: 62.1,
    featured: false,
  },
  {
    sku: "TP-240826-3375",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.5,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.98 x 6.41 x 3.98 mm",
    tablePercent: 63,
    depthPercent: 62.1,
    featured: false,
  },
  {
    sku: "TP-020825-2061",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.4,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.76 x 6.24 x 4.06 mm",
    tablePercent: 61,
    depthPercent: 65.1,
    featured: false,
  },
  {
    sku: "TP-080626-3293",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.35,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.08 x 6.10 x 3.76 mm",
    tablePercent: 61,
    depthPercent: 61.6,
    featured: false,
  },

  // Oval Polygon Step Cut
  {
    sku: "TP-290526-3282",
    shape: "oval",
    shapeName: "Oval Polygon Step Cut",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.06,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.25 x 5.37 x 3.27 mm",
    tablePercent: 62,
    depthPercent: 60.9,
    featured: false,
  },

  // Pear Brilliant
  {
    sku: "TP-030926-3383",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 2,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.27 x 6.92 x 4.31 mm",
    tablePercent: 61,
    depthPercent: 62.3,
    featured: false,
  },
  {
    sku: "TP-240225-979",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 1.91,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.78 x 6.75 x 4.51 mm",
    tablePercent: 61,
    depthPercent: 66.8,
    featured: false,
  },
  {
    sku: "TP-25056-3271",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 1.5,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.19 x 6.38 x 3.96 mm",
    tablePercent: 61,
    depthPercent: 62.1,
    featured: false,
  },

  // Portuguese Cut
  {
    sku: "TP-140725--1861",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.26,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.92 x 6.95 x 3.97 mm",
    tablePercent: 58,
    depthPercent: 57.2,
    featured: false,
  },
  {
    sku: "TP-140725--1958",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.09,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.50 x 6.51 x 4.02 mm",
    tablePercent: 55,
    depthPercent: 61.8,
    featured: false,
  },
  {
    sku: "TP-140725--1860",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.09,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.61 x 6.66 x 3.80 mm",
    tablePercent: 61,
    depthPercent: 57.4,
    featured: false,
  },
  {
    sku: "TP-250726-3365",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.07,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.45 x 6.44 x 3.73 mm",
    tablePercent: 59,
    depthPercent: 57.9,
    featured: false,
  },
  {
    sku: "TP-220725-2015",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.05,
    color: "D",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.48 x 6.48 x 3.83 mm",
    tablePercent: 58,
    depthPercent: 59.1,
    featured: false,
  },
  {
    sku: "TP-150826-3374",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.05,
    color: "E",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.40 x 6.39 x 3.84 mm",
    tablePercent: 58,
    depthPercent: 60.1,
    featured: false,
  },
  {
    sku: "TP-140725--1959",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.03,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.30 x 6.31 x 4.02 mm",
    tablePercent: 60,
    depthPercent: 63.7,
    featured: false,
  },
  {
    sku: "TP-250726-3364",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.37 x 6.38 x 3.61 mm",
    tablePercent: 68,
    depthPercent: 56.6,
    featured: false,
  },
  {
    sku: "TP-240826-3377",
    shape: "round",
    shapeName: "Portuguese Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.64,
    color: "D",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.42 x 5.41 x 3.18 mm",
    tablePercent: 64,
    depthPercent: 58.8,
    featured: false,
  },

  // Radiant Cut
  {
    sku: "TP-29125-913",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 1.59,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.12 x 5.77 x 4.10 mm",
    tablePercent: 67,
    depthPercent: 71.1,
    featured: false,
  },
  {
    sku: "TP-200226-3129",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 1.55,
    color: "E",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.26 x 5.90 x 3.72 mm",
    tablePercent: 60,
    depthPercent: 63.1,
    featured: false,
  },
  {
    sku: "TP-120325-1036",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 1.31,
    color: "D",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.04 x 5.35 x 3.70 mm",
    tablePercent: 62,
    depthPercent: 69.2,
    featured: false,
  },

  // Round Mixed Cut
  {
    sku: "TP-250726-3363",
    shape: "round",
    shapeName: "Round Mixed Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.03,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.37 x 6.40 x 4.10 mm",
    tablePercent: 60,
    depthPercent: 64.3,
    featured: false,
  },
  {
    sku: "TP-300426-3236",
    shape: "round",
    shapeName: "Round Mixed Cut",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.02,
    color: "E",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.48 x 6.50 x 3.94 mm",
    tablePercent: 55,
    depthPercent: 60.7,
    featured: false,
  },

  // Triangular Brilliant
  {
    sku: "TP-220526-3270",
    shape: "trillion",
    shapeName: "Triangular Brilliant",
    shapeCode: "TR",
    origin: "lab",
    carat: 4.56,
    color: "F",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.72 x 12.33 x 5.88 mm",
    tablePercent: 67,
    depthPercent: 47.7,
    featured: false,
  },

  // Fancy Intense Brownish Orange
  {
    sku: "TP-100126-3041",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 1,
    color: "Fancy Intense Brownish Orange",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Slight",
    lab: "IGI",
    measurements: "6.73 x 4.77 x 3.25 mm",
    tablePercent: 70,
    depthPercent: 68.1,
    featured: false,
  },

  // Fancy Intense Pinkish Orange
  {
    sku: "TP-100126-3026",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 2.02,
    color: "Fancy Intense Pinkish Orange",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "Slight",
    lab: "IGI",
    measurements: "8.93 x 6.49 x 4.29 mm",
    tablePercent: 62,
    depthPercent: 66.1,
    featured: false,
  },

  // Fancy Yellow Brown
  {
    sku: "TP-260825-2267",
    shape: "princess",
    shapeName: "Princess Cut",
    shapeCode: "PR",
    origin: "lab",
    carat: 4.01,
    color: "Fancy Yellow Brown",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.64 x 8.54 x 5.88 mm",
    tablePercent: 69,
    depthPercent: 68.9,
    featured: false,
  },
  {
    sku: "TP-150825-2206",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 3.01,
    color: "Fancy Yellow Brown",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "Very Slight",
    lab: "IGI",
    measurements: "8.13 x 7.77 x 5.28 mm",
    tablePercent: 62,
    depthPercent: 68,
    featured: false,
  },

  // Fancy Yellowish Brown
  {
    sku: "TP-130726-3357",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 4.01,
    color: "Fancy Yellowish Brown",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "12.78 x 8.90 x 5.38 mm",
    tablePercent: 60,
    depthPercent: 60.4,
    featured: false,
  },
  {
    sku: "TP-250626-3307",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 4,
    color: "Fancy Yellowish Brown",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "12.53 x 8.92 x 5.50 mm",
    tablePercent: 58,
    depthPercent: 61.7,
    featured: false,
  },
  {
    sku: "TP-260825-2265",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 3.01,
    color: "Fancy Yellowish Brown",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.13 x 7.05 x 4.69 mm",
    tablePercent: 69,
    depthPercent: 66.5,
    featured: false,
  },
  {
    sku: "TP-020726-3335",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 2.4,
    color: "Fancy Yellowish Brown",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.17 x 7.43 x 4.48 mm",
    tablePercent: 61,
    depthPercent: 60.3,
    featured: false,
  },

  // Fancy Vivid Orangy Yellow
  {
    sku: "TP-171125-2875",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.53,
    color: "Fancy Vivid Orangy Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.10 x 5.51 x 3.77 mm",
    tablePercent: 64,
    depthPercent: 68.4,
    featured: false,
  },
  {
    sku: "TP-171125-2874",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 1.53,
    color: "Fancy Vivid Orangy Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.51 x 5.33 x 3.93 mm",
    tablePercent: 67,
    depthPercent: 73.7,
    featured: false,
  },
  {
    sku: "TP-090925-2304",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.51,
    color: "Fancy Vivid Orangy Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.42 x 5.91 x 3.94 mm",
    tablePercent: 66,
    depthPercent: 66.7,
    featured: false,
  },

  // Fancy Vivid Yellow
  {
    sku: "TP-090925-2306",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.71,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.74 x 6.56 x 3.84 mm",
    tablePercent: 66,
    depthPercent: 58.5,
    featured: false,
  },
  {
    sku: "TP-030725-1698",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 1.55,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.06 x 5.67 x 3.83 mm",
    tablePercent: 70,
    depthPercent: 67.5,
    featured: false,
  },
  {
    sku: "TP-090925-2305",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.51,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.23 x 6.20 x 3.91 mm",
    tablePercent: 67,
    depthPercent: 63.1,
    featured: false,
  },
  {
    sku: "TP-040725-1815",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.5,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.08 x 5.86 x 3.65 mm",
    tablePercent: 70,
    depthPercent: 62.3,
    featured: false,
  },
  {
    sku: "TP-030725-1694",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.06,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.57 x 6.92 x 3.86 mm",
    tablePercent: 60,
    depthPercent: 55.8,
    featured: false,
  },
  {
    sku: "TP-030725-1699",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.03,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.55 x 4.49 x 3.11 mm",
    tablePercent: 68,
    depthPercent: 69.3,
    featured: false,
  },
  {
    sku: "TP-040725-1810",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.02,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.11 x 6.81 x 3.98 mm",
    tablePercent: 63,
    depthPercent: 58.4,
    featured: false,
  },
  {
    sku: "TP-030725-1689",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.64 x 5.64 x 3.45 mm",
    tablePercent: 64,
    depthPercent: 61.2,
    featured: false,
  },
  {
    sku: "TP-030725-1697",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.77 x 6.74 x 4.07 mm",
    tablePercent: 61,
    depthPercent: 60.4,
    featured: false,
  },
  {
    sku: "TP-030725-1683",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.59 x 5.69 x 3.46 mm",
    tablePercent: 67,
    depthPercent: 60.8,
    featured: false,
  },
  {
    sku: "TP-030725-1737",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.52 x 5.61 x 3.27 mm",
    tablePercent: 67,
    depthPercent: 58.3,
    featured: false,
  },
  {
    sku: "TP-030725-1680",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Yellow",
    clarity: "SI1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.66 x 5.57 x 3.34 mm",
    tablePercent: 65,
    depthPercent: 60,
    featured: false,
  },
  {
    sku: "TP-010925-2276",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.51 x 5.25 x 3.46 mm",
    tablePercent: 69,
    depthPercent: 65.9,
    featured: false,
  },
  {
    sku: "TP-030725-1695",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.80 x 6.72 x 3.99 mm",
    tablePercent: 62,
    depthPercent: 59.4,
    featured: false,
  },
  {
    sku: "TP-030725-1704",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 0.99,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.60 x 5.55 x 3.41 mm",
    tablePercent: 66,
    depthPercent: 61.4,
    featured: false,
  },
  {
    sku: "TP-030725-1705",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 0.99,
    color: "Fancy Vivid Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.65 x 5.64 x 3.57 mm",
    tablePercent: 65,
    depthPercent: 63.3,
    featured: false,
  },
  {
    sku: "TP-030725-1706",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 0.96,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.87 x 6.82 x 3.63 mm",
    tablePercent: 67,
    depthPercent: 53.2,
    featured: false,
  },
  {
    sku: "TP-260625-1616",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 0.92,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.07 x 5.01 x 3.04 mm",
    tablePercent: 72,
    depthPercent: 60.7,
    featured: false,
  },
  {
    sku: "TP-260625-1615",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 0.91,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.88 x 4.64 x 3.19 mm",
    tablePercent: 68,
    depthPercent: 68.8,
    featured: false,
  },
  {
    sku: "TP-230726-3362",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 0.9,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.80 x 5.63 x 3.28 mm",
    tablePercent: 66,
    depthPercent: 58.3,
    featured: false,
  },

  // Fancy Intense Blue
  {
    sku: "TP-11-23-156",
    shape: "asscher",
    shapeName: "Asscher Cut",
    shapeCode: "AS",
    origin: "lab",
    carat: 3.03,
    color: "Fancy Intense Blue",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.09 x 8.03 x 4.78 mm",
    tablePercent: 66,
    depthPercent: 59.5,
    featured: false,
  },

  // Fancy Vivid Blue
  {
    sku: "TP-310526-3290",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 3.41,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.73 x 7.05 x 4.41 mm",
    tablePercent: 69,
    depthPercent: 62.6,
    featured: false,
  },
  {
    sku: "TP-180426-3210",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 2.4,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.87 x 6.57 x 4.13 mm",
    tablePercent: 61,
    depthPercent: 62.9,
    featured: false,
  },
  {
    sku: "TP-230726-3361",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 2.06,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.43 x 7.39 x 4.44 mm",
    tablePercent: 66,
    depthPercent: 60.1,
    featured: false,
  },
  {
    sku: "TP-080525-1305",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 2.03,
    color: "Fancy Vivid Blue",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.92 x 5.88 x 3.92 mm",
    tablePercent: 59,
    depthPercent: 66.7,
    featured: false,
  },
  {
    sku: "TP-11-23-5",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 2.03,
    color: "Fancy Vivid Blue",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.07 x 7.16 x 4.36 mm",
    tablePercent: 59,
    depthPercent: 60.9,
    featured: false,
  },
  {
    sku: "TP-040725-1743",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 2,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.22 x 5.73 x 4.25 mm",
    tablePercent: 62,
    depthPercent: 74.2,
    featured: false,
  },
  {
    sku: "TP-180426-3212",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.97,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.06 x 5.94 x 3.95 mm",
    tablePercent: 63,
    depthPercent: 66.5,
    featured: false,
  },
  {
    sku: "TP-250626-3325",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.83,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "12.85 x 6.25 x 3.14 mm",
    tablePercent: 70,
    depthPercent: 50.2,
    featured: false,
  },
  {
    sku: "TP-180426-3211",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.6,
    color: "Fancy Vivid Blue",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "12.11 x 5.75 x 3.38 mm",
    tablePercent: 67,
    depthPercent: 58.8,
    featured: false,
  },
  {
    sku: "TP-040725-1786",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.58,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.78 x 5.79 x 3.52 mm",
    tablePercent: 65,
    depthPercent: 60.8,
    featured: false,
  },
  {
    sku: "TP-140725--1869",
    shape: "asscher",
    shapeName: "Asscher Cut",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.56,
    color: "Fancy Vivid Blue",
    clarity: "VVS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.49 x 6.41 x 3.82 mm",
    tablePercent: 66,
    depthPercent: 59.6,
    featured: false,
  },
  {
    sku: "TP-140725--1882",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.54,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.51 x 6.30 x 4.40 mm",
    tablePercent: 66,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "TP-040725-1787",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.53,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.02 x 5.36 x 3.47 mm",
    tablePercent: 66,
    depthPercent: 64.7,
    featured: false,
  },
  {
    sku: "TP-030725-1712",
    shape: "radiant",
    shapeName: "Radiant Cut",
    shapeCode: "RA",
    origin: "lab",
    carat: 1.53,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.96 x 5.68 x 3.95 mm",
    tablePercent: 63,
    depthPercent: 69.5,
    featured: false,
  },
  {
    sku: "TP-040725-1774",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.51,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.18 x 5.18 x 3.37 mm",
    tablePercent: 68,
    depthPercent: 65.1,
    featured: false,
  },
  {
    sku: "TP-040725-1766",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.51,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.50 x 5.35 x 3.70 mm",
    tablePercent: 64,
    depthPercent: 69.2,
    featured: false,
  },
  {
    sku: "TP-030725-1711",
    shape: "marquise",
    shapeName: "Marquise Brilliant",
    shapeCode: "MQ",
    origin: "lab",
    carat: 1.51,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "11.13 x 6.23 x 3.71 mm",
    tablePercent: 64,
    depthPercent: 59.6,
    featured: false,
  },
  {
    sku: "TP-040725-1746",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 1.51,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "10.60 x 6.27 x 3.75 mm",
    tablePercent: 59,
    depthPercent: 59.8,
    featured: false,
  },
  {
    sku: "TP-040725-1779",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.5,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "9.11 x 6.56 x 3.95 mm",
    tablePercent: 58,
    depthPercent: 60.2,
    featured: false,
  },
  {
    sku: "TP-040725-1764",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.11,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.80 x 4.75 x 3.56 mm",
    tablePercent: 61,
    depthPercent: 74.9,
    featured: false,
  },
  {
    sku: "TP-140725--1890",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.1,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.56 x 7.15 x 3.87 mm",
    tablePercent: 60,
    depthPercent: 54.1,
    featured: false,
  },
  {
    sku: "TP-140725--1893",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.1,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.29 x 7.02 x 3.97 mm",
    tablePercent: 64,
    depthPercent: 56.6,
    featured: false,
  },
  {
    sku: "TP-030725-1709",
    shape: "pear",
    shapeName: "Pear Brilliant",
    shapeCode: "PS",
    origin: "lab",
    carat: 1.1,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.98 x 5.55 x 3.79 mm",
    tablePercent: 65,
    depthPercent: 68.3,
    featured: false,
  },
  {
    sku: "TP-140725--1894",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.09,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.32 x 6.97 x 4.23 mm",
    tablePercent: 60,
    depthPercent: 60.7,
    featured: false,
  },
  {
    sku: "TP-140725--1865",
    shape: "princess",
    shapeName: "Princess Cut",
    shapeCode: "PR",
    origin: "lab",
    carat: 1.09,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.52 x 5.50 x 3.98 mm",
    tablePercent: 67,
    depthPercent: 72.4,
    featured: false,
  },
  {
    sku: "TP-040725-1826",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.09,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.05 x 5.75 x 3.70 mm",
    tablePercent: 59,
    depthPercent: 64.3,
    featured: false,
  },
  {
    sku: "TP-140725--1892",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.07,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.23 x 6.76 x 4.12 mm",
    tablePercent: 60,
    depthPercent: 60.9,
    featured: false,
  },
  {
    sku: "TP-040725-1769",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.07,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.21 x 6.95 x 3.89 mm",
    tablePercent: 61,
    depthPercent: 56,
    featured: false,
  },
  {
    sku: "TP-140725--1881",
    shape: "asscher",
    shapeName: "Asscher Cut",
    shapeCode: "AS",
    origin: "lab",
    carat: 1.07,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.68 x 5.68 x 3.42 mm",
    tablePercent: 62,
    depthPercent: 60.2,
    featured: false,
  },
  {
    sku: "TP-040725-1790",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.07,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.74 x 5.72 x 3.71 mm",
    tablePercent: 68,
    depthPercent: 64.9,
    featured: false,
  },
  {
    sku: "TP-140725--1891",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.05,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.01 x 6.98 x 3.96 mm",
    tablePercent: 64,
    depthPercent: 56.7,
    featured: false,
  },
  {
    sku: "TP-140725--1870",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.05,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.70 x 5.54 x 3.90 mm",
    tablePercent: 66,
    depthPercent: 70.4,
    featured: false,
  },
  {
    sku: "TP-110425-1237",
    shape: "round",
    shapeName: "Round Brilliant",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.04,
    color: "Fancy Vivid Blue",
    clarity: "VS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.46 x 6.48 x 4.03 mm",
    tablePercent: 57,
    depthPercent: 62.3,
    featured: false,
  },
  {
    sku: "TP-040725-1791",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.04,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.70 x 5.62 x 3.75 mm",
    tablePercent: 65,
    depthPercent: 66.7,
    featured: false,
  },
  {
    sku: "TP-040725-1770",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.03,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.83 x 7.12 x 3.90 mm",
    tablePercent: 64,
    depthPercent: 54.8,
    featured: false,
  },
  {
    sku: "TP-040725-1758",
    shape: "princess",
    shapeName: "Princess Cut",
    shapeCode: "PR",
    origin: "lab",
    carat: 1.03,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.46 x 5.42 x 3.96 mm",
    tablePercent: 68,
    depthPercent: 73.1,
    featured: false,
  },
  {
    sku: "TP-040725-1825",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1.03,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.20 x 5.64 x 3.62 mm",
    tablePercent: 61,
    depthPercent: 64.2,
    featured: false,
  },
  {
    sku: "TP-040725-1754",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.03,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.64 x 5.61 x 3.63 mm",
    tablePercent: 71,
    depthPercent: 64.7,
    featured: false,
  },
  {
    sku: "TP-040725-1796",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.03,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.50 x 5.48 x 4.17 mm",
    tablePercent: 66,
    depthPercent: 76.1,
    featured: false,
  },
  {
    sku: "TP-140725--1884",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.03,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.68 x 5.65 x 3.68 mm",
    tablePercent: 64,
    depthPercent: 65.1,
    featured: false,
  },
  {
    sku: "TP-030425-1208",
    shape: "round",
    shapeName: "Round Brilliant",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.02,
    color: "Fancy Vivid Blue",
    clarity: "VS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.49 x 6.50 x 3.93 mm",
    tablePercent: 58,
    depthPercent: 60.5,
    featured: false,
  },
  {
    sku: "TP-040725-1771",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.02,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.72 x 5.69 x 3.62 mm",
    tablePercent: 66,
    depthPercent: 63.6,
    featured: false,
  },
  {
    sku: "TP-140725--1901",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.41 x 6.63 x 4.10 mm",
    tablePercent: 59,
    depthPercent: 61.8,
    featured: false,
  },
  {
    sku: "TP-040725-1765",
    shape: "emerald",
    shapeName: "Emerald Cut",
    shapeCode: "EM",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.27 x 4.49 x 2.97 mm",
    tablePercent: 67,
    depthPercent: 66.1,
    featured: false,
  },
  {
    sku: "TP-040725-1757",
    shape: "princess",
    shapeName: "Princess Cut",
    shapeCode: "PR",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.40 x 5.39 x 3.90 mm",
    tablePercent: 66,
    depthPercent: 72.4,
    featured: false,
  },
  {
    sku: "TP-040725-1761",
    shape: "princess",
    shapeName: "Princess Cut",
    shapeCode: "PR",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.57 x 5.55 x 3.67 mm",
    tablePercent: 69,
    depthPercent: 66.1,
    featured: false,
  },
  {
    sku: "TP-040725-1792",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.74 x 5.70 x 3.80 mm",
    tablePercent: 63,
    depthPercent: 66.7,
    featured: false,
  },
  {
    sku: "TP-140725--1903",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.53 x 5.50 x 3.76 mm",
    tablePercent: 66,
    depthPercent: 68.4,
    featured: false,
  },
  {
    sku: "TP-140725--1904",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.59 x 5.50 x 3.74 mm",
    tablePercent: 65,
    depthPercent: 68,
    featured: false,
  },
  {
    sku: "TP-040725-1744",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.68 x 5.62 x 3.59 mm",
    tablePercent: 64,
    depthPercent: 63.9,
    featured: false,
  },
  {
    sku: "TP-140725--1875",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.60 x 5.50 x 3.81 mm",
    tablePercent: 66,
    depthPercent: 69.3,
    featured: false,
  },
  {
    sku: "TP-140725--1895",
    shape: "hexagon",
    shapeName: "Hexagonal",
    shapeCode: "HX",
    origin: "lab",
    carat: 1.01,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.42 x 5.76 x 3.98 mm",
    tablePercent: 64,
    depthPercent: 69.1,
    featured: false,
  },
  {
    sku: "TP-030425-1206",
    shape: "round",
    shapeName: "Round Brilliant",
    shapeCode: "RD",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    cut: "Very Good",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.24 x 6.29 x 4.00 mm",
    tablePercent: 60,
    depthPercent: 63.7,
    featured: false,
  },
  {
    sku: "TP-140725--1902",
    shape: "heart",
    shapeName: "Heart Brilliant",
    shapeCode: "HT",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.03 x 7.29 x 3.72 mm",
    tablePercent: 64,
    depthPercent: 51,
    featured: false,
  },
  {
    sku: "TP-140725--1897",
    shape: "princess",
    shapeName: "Princess Cut",
    shapeCode: "PR",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.62 x 5.48 x 3.91 mm",
    tablePercent: 71,
    depthPercent: 71.4,
    featured: false,
  },
  {
    sku: "TP-040725-1822",
    shape: "oval",
    shapeName: "Oval Brilliant",
    shapeCode: "OV",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "8.15 x 5.55 x 3.45 mm",
    tablePercent: 60,
    depthPercent: 62.2,
    featured: false,
  },
  {
    sku: "TP-030725-1678",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.67 x 5.63 x 3.51 mm",
    tablePercent: 66,
    depthPercent: 62.3,
    featured: false,
  },
  {
    sku: "TP-040725-1773",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.91 x 5.79 x 3.60 mm",
    tablePercent: 63,
    depthPercent: 62.2,
    featured: false,
  },
  {
    sku: "TP-140725--1883",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.67 x 5.63 x 3.59 mm",
    tablePercent: 63,
    depthPercent: 63.8,
    featured: false,
  },
  {
    sku: "TP-140725--1905",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.63 x 5.54 x 3.75 mm",
    tablePercent: 62,
    depthPercent: 67.7,
    featured: false,
  },
  {
    sku: "TP-040725-1798",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.73 x 5.57 x 3.66 mm",
    tablePercent: 64,
    depthPercent: 65.7,
    featured: false,
  },
  {
    sku: "TP-040725-1797",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 1,
    color: "Fancy Vivid Blue",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.67 x 5.64 x 3.66 mm",
    tablePercent: 69,
    depthPercent: 64.9,
    featured: false,
  },
  {
    sku: "TP-130625-1403",
    shape: "asscher",
    shapeName: "Asscher Cut",
    shapeCode: "AS",
    origin: "lab",
    carat: 0.99,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.12 x 5.07 x 3.80 mm",
    tablePercent: 64,
    depthPercent: 75,
    featured: false,
  },
  {
    sku: "TP-040725-1808",
    shape: "princess",
    shapeName: "Princess Cut",
    shapeCode: "PR",
    origin: "lab",
    carat: 0.99,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.35 x 5.33 x 3.87 mm",
    tablePercent: 67,
    depthPercent: 72.6,
    featured: false,
  },
  {
    sku: "TP-040725-1806",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 0.99,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.56 x 5.57 x 3.75 mm",
    tablePercent: 63,
    depthPercent: 67.3,
    featured: false,
  },
  {
    sku: "TP-040725-1829",
    shape: "cushion",
    shapeName: "Cushion Brilliant",
    shapeCode: "CU",
    origin: "lab",
    carat: 0.99,
    color: "Fancy Vivid Blue",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.55 x 5.53 x 3.70 mm",
    tablePercent: 63,
    depthPercent: 66.9,
    featured: false,
  },
];
