import type { Stone } from "./stones";

/**
 * Real natural stock, supplied by the trade desk. As in real-stones.ts, report
 * numbers are left out of this file — they are shared on enquiry only.
 *
 * The supplier's client reference ("OM-1026") is used as the SKU.
 *
 * Report numbers in this batch are GIA's ten-digit format, so `lab` is GIA.
 *
 * Supplier abbreviations are normalised to the site's vocabulary: polish and
 * symmetry EX/VG/G/F become Excellent/Very Good/Good/Fair; fluorescence MB and
 * MW (medium blue/white) file under Medium, STB/STG/SB under Strong.
 * "Cut-Cornered" (GIA's cut-cornered rectangular modified brilliant) files
 * under "radiant", which is the same outline.
 *
 * `color` holds the report's fancy-colour wording, or a GIA letter range
 * ("W-X", "Y-Z") for stones below the D–J scale this catalogue filters on;
 * `isColorGrade()` treats both as non-D–J, so they sit under "Fancy".
 */
export const REAL_NATURAL_STONES: Stone[] = [
  {
    sku: "OM-1026",
    shape: "asscher",
    shapeName: "Asscher",
    shapeCode: "AS",
    origin: "natural",
    carat: 1.03,
    color: "Fancy Light Yellow",
    clarity: "VS1",
    polish: "Good",
    symmetry: "Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "5.38 x 4.89 x 3.85 mm",
    tablePercent: 58,
    depthPercent: 78.7,
    featured: false,
  },
  {
    sku: "OM-1027",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 1,
    color: "Fancy Yellow",
    clarity: "SI2",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.30 x 6.24 x 3.73 mm",
    tablePercent: 62,
    depthPercent: 59.7,
    featured: false,
  },
  {
    sku: "OM-1035",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.35,
    color: "Fancy Light Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Strong",
    lab: "GIA",
    measurements: "6.14 x 5.95 x 3.96 mm",
    tablePercent: 59,
    depthPercent: 66.6,
    featured: false,
  },
  {
    sku: "OM-1036",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.55,
    color: "Fancy Intense Yellow",
    clarity: "SI1",
    polish: "Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "6.03 x 4.91 x 2.57 mm",
    tablePercent: 68,
    depthPercent: 52.3,
    featured: false,
  },
  {
    sku: "OM-1038",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 2,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "6.73 x 6.56 x 4.75 mm",
    tablePercent: 60,
    depthPercent: 72.4,
    featured: false,
  },
  {
    sku: "OM-1046",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 2.01,
    color: "W-X",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "7.42 x 5.61 x 5.06 mm",
    tablePercent: 55,
    depthPercent: 90.2,
    featured: false,
  },
  {
    sku: "OM-1048",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.28 x 3.95 x 3.11 mm",
    tablePercent: 58,
    depthPercent: 78.8,
    featured: false,
  },
  {
    sku: "OM-1051",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 1,
    color: "Fancy Light Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.53 x 6.09 x 3.60 mm",
    tablePercent: 59,
    depthPercent: 59.1,
    featured: false,
  },
  {
    sku: "OM-1054",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Intense Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "4.04 x 5.03 x 3.00 mm",
    tablePercent: 53,
    depthPercent: 59.6,
    featured: false,
  },
  {
    sku: "OM-1055",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "4.23 x 5.04 x 2.83 mm",
    tablePercent: 57,
    depthPercent: 56.1,
    featured: false,
  },
  {
    sku: "OM-1058",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 1,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Fair",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.66 x 4.60 x 3.62 mm",
    tablePercent: 52,
    depthPercent: 78.7,
    featured: false,
  },
  {
    sku: "OM-1059",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Fancy Pinkish Brown",
    clarity: "I2",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "5.61 x 5.33 x 3.79 mm",
    tablePercent: 60,
    depthPercent: 71,
    featured: false,
  },
  {
    sku: "OM-1067",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Light Purplish Pink",
    clarity: "SI2",
    polish: "Very Good",
    symmetry: "Fair",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.27 x 3.96 x 3.18 mm",
    tablePercent: 58,
    depthPercent: 80.4,
    featured: false,
  },
  {
    sku: "OM-1071",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.61 x 5.08 x 3.73 mm",
    tablePercent: 60,
    depthPercent: 73.3,
    featured: false,
  },
  {
    sku: "OM-1075",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Y-Z",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.14 x 5.09 x 3.99 mm",
    tablePercent: 58,
    depthPercent: 78.3,
    featured: false,
  },
  {
    sku: "OM-1101",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.71,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.54 x 4.59 x 3.10 mm",
    tablePercent: 55,
    depthPercent: 67.5,
    featured: false,
  },
  {
    sku: "OM-1104",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 1,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.76 x 6.51 x 3.33 mm",
    tablePercent: 66,
    depthPercent: 51.2,
    featured: false,
  },
  {
    sku: "OM-1105",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.77,
    color: "Fancy Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "5.85 x 4.45 x 3.19 mm",
    tablePercent: 57,
    depthPercent: 71.7,
    featured: false,
  },
  {
    sku: "OM-1114",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.15,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.80 x 5.50 x 3.88 mm",
    tablePercent: 60,
    depthPercent: 70.6,
    featured: false,
  },
  {
    sku: "OM-1116",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.1,
    color: "Fancy Light Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "6.00 x 5.29 x 3.70 mm",
    tablePercent: 62,
    depthPercent: 69.9,
    featured: false,
  },
  {
    sku: "OM-1117",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.86 x 5.04 x 3.51 mm",
    tablePercent: 64,
    depthPercent: 69.7,
    featured: false,
  },
  {
    sku: "OM-1132",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Y-Z",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "5.26 x 5.16 x 3.81 mm",
    tablePercent: 60,
    depthPercent: 73.8,
    featured: false,
  },
  {
    sku: "OM-1137",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.34,
    color: "Fancy Deep Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Strong",
    lab: "GIA",
    measurements: "5.75 x 5.73 x 4.09 mm",
    tablePercent: 64,
    depthPercent: 71.4,
    featured: false,
  },
  {
    sku: "OM-1144",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.18 x 5.07 x 3.89 mm",
    tablePercent: 60,
    depthPercent: 76.8,
    featured: false,
  },
  {
    sku: "OM-1145",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.32 x 5.28 x 3.81 mm",
    tablePercent: 58,
    depthPercent: 72.3,
    featured: false,
  },
  {
    sku: "OM-1170",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "W-X",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.27 x 4.93 x 3.90 mm",
    tablePercent: 57,
    depthPercent: 79,
    featured: false,
  },
  {
    sku: "OM-1175",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Y-Z",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.13 x 4.99 x 3.96 mm",
    tablePercent: 66,
    depthPercent: 79.3,
    featured: false,
  },
  {
    sku: "OM-1179",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.19,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.64 x 5.59 x 3.90 mm",
    tablePercent: 62,
    depthPercent: 69.7,
    featured: false,
  },
  {
    sku: "OM-1187",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.22,
    color: "Fancy Light Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.13 x 5.41 x 3.88 mm",
    tablePercent: 58,
    depthPercent: 71.8,
    featured: false,
  },
  {
    sku: "OM-1195",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.62,
    color: "Fancy Intense Yellow",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.08 x 4.33 x 3.06 mm",
    tablePercent: 61,
    depthPercent: 70.7,
    featured: false,
  },
  {
    sku: "OM-1210",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 0.55,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.70 x 4.99 x 3.01 mm",
    tablePercent: 60,
    depthPercent: 60.3,
    featured: false,
  },
  {
    sku: "OM-1211",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 3,
    color: "U-V",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "7.90 x 7.74 x 5.14 mm",
    tablePercent: 60,
    depthPercent: 66.3,
    featured: false,
  },
  {
    sku: "OM-1219",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "4.83 x 6.08 x 3.86 mm",
    tablePercent: 61,
    depthPercent: 63.6,
    featured: false,
  },
  {
    sku: "OM-1225",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.14,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.81 x 5.44 x 3.80 mm",
    tablePercent: 60,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "OM-1244",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "U-V",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.24 x 5.25 x 3.47 mm",
    tablePercent: 56,
    depthPercent: 66,
    featured: false,
  },
  {
    sku: "OM-1255",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 1.14,
    color: "Fancy Light Yellow",
    clarity: "SI2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "7.42 x 5.33 x 3.57 mm",
    tablePercent: 59,
    depthPercent: 67,
    featured: false,
  },
  {
    sku: "OM-1279",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1,
    color: "Fancy Intense Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.95 x 4.92 x 3.44 mm",
    tablePercent: 57,
    depthPercent: 69.9,
    featured: false,
  },
  {
    sku: "OM-1280",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.21 x 4.97 x 3.50 mm",
    tablePercent: 60,
    depthPercent: 70.4,
    featured: false,
  },
  {
    sku: "OM-1297",
    shape: "radiant",
    shapeName: "Cut-Cornered Rectangular",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.62,
    color: "Fancy Intense Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.37 x 4.24 x 2.84 mm",
    tablePercent: 70,
    depthPercent: 67,
    featured: false,
  },
  {
    sku: "OM-1312",
    shape: "asscher",
    shapeName: "Asscher",
    shapeCode: "AS",
    origin: "natural",
    carat: 1.14,
    color: "Fancy Deep Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.40 x 5.38 x 4.01 mm",
    tablePercent: 64,
    depthPercent: 74.7,
    featured: false,
  },
  {
    sku: "OM-1341",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.8,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.03 x 4.99 x 3.49 mm",
    tablePercent: 59,
    depthPercent: 69.9,
    featured: false,
  },
  {
    sku: "OM-1345",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Light Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.71 x 5.06 x 3.53 mm",
    tablePercent: 67,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "OM-1347",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 1,
    color: "Y-Z",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "7.40 x 4.88 x 3.51 mm",
    tablePercent: 58,
    depthPercent: 72,
    featured: false,
  },
  {
    sku: "OM-1348",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.35 x 5.34 x 3.71 mm",
    tablePercent: 64,
    depthPercent: 69.4,
    featured: false,
  },
  {
    sku: "OM-1351",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 2.01,
    color: "S-T",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "9.83 x 6.21 x 4.25 mm",
    tablePercent: 62,
    depthPercent: 68.4,
    featured: false,
  },
  {
    sku: "OM-1357",
    shape: "asscher",
    shapeName: "Asscher",
    shapeCode: "AS",
    origin: "natural",
    carat: 0.6,
    color: "Fancy Intense Orangy Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.44 x 4.44 x 3.16 mm",
    tablePercent: 64,
    depthPercent: 71.3,
    featured: false,
  },
  {
    sku: "OM-1364",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 2.26,
    color: "Fancy Brownish Greenish Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "GIA",
    measurements: "10.69 x 6.64 x 4.28 mm",
    tablePercent: 64,
    depthPercent: 64.6,
    featured: false,
  },
  {
    sku: "OM-1370",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 3.01,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "GIA",
    measurements: "8.42 x 7.32 x 5.12 mm",
    tablePercent: 60,
    depthPercent: 69.9,
    featured: false,
  },
  {
    sku: "OM-1407",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Intense Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "5.87 x 6.28 x 3.56 mm",
    tablePercent: 65,
    depthPercent: 56.7,
    featured: false,
  },
  {
    sku: "OM-1429",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.51,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "4.46 x 4.17 x 2.86 mm",
    tablePercent: 64,
    depthPercent: 68.6,
    featured: false,
  },
  {
    sku: "OM-1431",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.53,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "4.60 x 4.25 x 2.87 mm",
    tablePercent: 65,
    depthPercent: 67.7,
    featured: false,
  },
  {
    sku: "OM-1441",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.51,
    color: "Fancy Vivid Yellow",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.99 x 3.85 x 2.69 mm",
    tablePercent: 59,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "OM-1443",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 0.52,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.52 x 5.29 x 2.85 mm",
    tablePercent: 61,
    depthPercent: 53.9,
    featured: false,
  },
  {
    sku: "OM-1444",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.52,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "6.68 x 4.02 x 2.62 mm",
    tablePercent: 60,
    depthPercent: 65.2,
    featured: false,
  },
  {
    sku: "OM-1449",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.9,
    color: "Fancy Vivid Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.17 x 5.13 x 3.57 mm",
    tablePercent: 61,
    depthPercent: 69.5,
    featured: false,
  },
  {
    sku: "OM-1455",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 1.01,
    color: "Y-Z",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "9.00 x 5.19 x 3.01 mm",
    tablePercent: 65,
    depthPercent: 58,
    featured: false,
  },
  {
    sku: "OM-1480",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 2.02,
    color: "Fancy Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "7.54 x 6.22 x 4.32 mm",
    tablePercent: 57,
    depthPercent: 69.5,
    featured: false,
  },
  {
    sku: "OM-1481",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1.21,
    color: "Fancy Intense Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.67 x 5.11 x 3.55 mm",
    tablePercent: 63,
    depthPercent: 69.5,
    featured: false,
  },
  {
    sku: "OM-1482",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.76,
    color: "Fancy Brown-Pink",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.97 x 4.30 x 3.00 mm",
    tablePercent: 62,
    depthPercent: 69.9,
    featured: false,
  },
  {
    sku: "OM-1485",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1.02,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "Strong",
    lab: "GIA",
    measurements: "5.98 x 4.96 x 3.46 mm",
    tablePercent: 61,
    depthPercent: 69.6,
    featured: false,
  },
  {
    sku: "OM-1491",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "4.76 x 3.87 x 2.69 mm",
    tablePercent: 66,
    depthPercent: 69.5,
    featured: false,
  },
  {
    sku: "OM-1494",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 1.27,
    color: "Fancy Grayish Greenish Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "8.74 x 5.42 x 3.62 mm",
    tablePercent: 59,
    depthPercent: 66.8,
    featured: false,
  },
  {
    sku: "OM-1497",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.81,
    color: "Fancy Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.51 x 4.72 x 3.29 mm",
    tablePercent: 63,
    depthPercent: 69.6,
    featured: false,
  },
  {
    sku: "OM-1499",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.16 x 5.15 x 3.85 mm",
    tablePercent: 65,
    depthPercent: 74.8,
    featured: false,
  },
  {
    sku: "OM-1500",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "W-X",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.57 x 5.11 x 3.68 mm",
    tablePercent: 58,
    depthPercent: 72,
    featured: false,
  },
  {
    sku: "OM-1504",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.32,
    color: "Fancy Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "6.01 x 5.73 x 3.99 mm",
    tablePercent: 62,
    depthPercent: 69.7,
    featured: false,
  },
  {
    sku: "OM-1505",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.5,
    color: "Light Pink",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.58 x 4.56 x 2.82 mm",
    tablePercent: 59,
    depthPercent: 61.8,
    featured: false,
  },
  {
    sku: "OM-1506",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.06 x 4.87 x 3.38 mm",
    tablePercent: 61,
    depthPercent: 69.4,
    featured: false,
  },
  {
    sku: "OM-1507",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "6.40 x 3.94 x 2.67 mm",
    tablePercent: 63,
    depthPercent: 67.7,
    featured: false,
  },
  {
    sku: "OM-1508",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Intense Yellow",
    clarity: "SI2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "9.49 x 4.66 x 3.24 mm",
    tablePercent: 57,
    depthPercent: 69.6,
    featured: false,
  },
  {
    sku: "OM-1509",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 0.5,
    color: "Light Pink",
    clarity: "SI2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.79 x 4.04 x 2.70 mm",
    tablePercent: 58,
    depthPercent: 66.8,
    featured: false,
  },
  {
    sku: "OM-1514",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 1.02,
    color: "Fancy Intense Yellow",
    clarity: "SI2",
    polish: "Good",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "9.06 x 5.45 x 2.30 mm",
    tablePercent: 69,
    depthPercent: 42.2,
    featured: false,
  },
  {
    sku: "OM-1515",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 0.73,
    color: "Fancy Light Yellow",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "6.31 x 4.47 x 3.10 mm",
    tablePercent: 60,
    depthPercent: 69.3,
    featured: false,
  },
  {
    sku: "OM-1520",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Light Yellow",
    clarity: "SI2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "8.32 x 4.89 x 3.34 mm",
    tablePercent: 61,
    depthPercent: 68.1,
    featured: false,
  },
  {
    sku: "OM-1523",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 5.02,
    color: "Fancy Light Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "13.50 x 8.50 x 5.80 mm",
    tablePercent: 63,
    depthPercent: 68.2,
    featured: false,
  },
  {
    sku: "OM-1524",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.52,
    color: "Fancy Intense Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.40 x 4.04 x 2.75 mm",
    tablePercent: 59,
    depthPercent: 68.2,
    featured: false,
  },
  {
    sku: "OM-1525",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.73,
    color: "Fancy Intense Yellow",
    clarity: "SI2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "7.54 x 4.58 x 2.89 mm",
    tablePercent: 61,
    depthPercent: 63.3,
    featured: false,
  },
  {
    sku: "OM-1526",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Light Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "7.37 x 4.95 x 3.39 mm",
    tablePercent: 58,
    depthPercent: 68.6,
    featured: false,
  },
  {
    sku: "OM-1527",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.02,
    color: "Fancy Yellow",
    clarity: "VVS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.45 x 5.31 x 3.60 mm",
    tablePercent: 67,
    depthPercent: 67.9,
    featured: false,
  },
  {
    sku: "OM-1528",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.91,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.14 x 5.04 x 3.50 mm",
    tablePercent: 66,
    depthPercent: 69.4,
    featured: false,
  },
  {
    sku: "OM-1529",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.7,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.42 x 4.34 x 3.00 mm",
    tablePercent: 64,
    depthPercent: 69.1,
    featured: false,
  },
  {
    sku: "OM-1532",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.11 x 3.77 x 2.64 mm",
    tablePercent: 64,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "OM-1533",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.53,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Very Good",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.99 x 4.03 x 2.70 mm",
    tablePercent: 68,
    depthPercent: 67,
    featured: false,
  },
  {
    sku: "OM-1534",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.51,
    color: "Fancy Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "4.79 x 3.91 x 2.73 mm",
    tablePercent: 65,
    depthPercent: 70,
    featured: false,
  },
  {
    sku: "OM-1535",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.52,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.91 x 3.89 x 2.71 mm",
    tablePercent: 66,
    depthPercent: 69.6,
    featured: false,
  },
  {
    sku: "OM-1536",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.61,
    color: "Fancy Intense Yellow",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.02 x 4.18 x 2.88 mm",
    tablePercent: 62,
    depthPercent: 68.8,
    featured: false,
  },
  {
    sku: "OM-1537",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.63,
    color: "Fancy Intense Yellow",
    clarity: "VVS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.11 x 4.16 x 2.90 mm",
    tablePercent: 67,
    depthPercent: 69.6,
    featured: false,
  },
  {
    sku: "OM-1538",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "5.35 x 5.34 x 3.69 mm",
    tablePercent: 62,
    depthPercent: 69.1,
    featured: false,
  },
  {
    sku: "OM-1539",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.33 x 5.32 x 3.65 mm",
    tablePercent: 65,
    depthPercent: 68.6,
    featured: false,
  },
  {
    sku: "OM-1541",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 0.83,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.00 x 4.96 x 3.44 mm",
    tablePercent: 65,
    depthPercent: 69.2,
    featured: false,
  },
  {
    sku: "OM-1545",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 0.61,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "4.70 x 5.15 x 3.10 mm",
    tablePercent: 63,
    depthPercent: 60.2,
    featured: false,
  },
  {
    sku: "OM-1546",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Intense Yellow",
    clarity: "VVS2",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.95 x 4.14 x 2.56 mm",
    tablePercent: 58,
    depthPercent: 61.7,
    featured: false,
  },
  {
    sku: "OM-1547",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.56,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.98 x 4.07 x 2.81 mm",
    tablePercent: 64,
    depthPercent: 69.1,
    featured: false,
  },
  {
    sku: "OM-1548",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.7,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.37 x 4.31 x 2.98 mm",
    tablePercent: 69,
    depthPercent: 69.2,
    featured: false,
  },
  {
    sku: "OM-1549",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1,
    color: "Fancy Light Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.88 x 4.89 x 3.43 mm",
    tablePercent: 67,
    depthPercent: 70.02,
    featured: false,
  },
  {
    sku: "OM-1551",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.26 x 5.11 x 3.85 mm",
    tablePercent: 63,
    depthPercent: 75.3,
    featured: false,
  },
  {
    sku: "OM-1553",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.73,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.73 x 4.34 x 2.99 mm",
    tablePercent: 64,
    depthPercent: 69.1,
    featured: false,
  },
  {
    sku: "OM-1554",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1.01,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "6.17 x 4.87 x 3.40 mm",
    tablePercent: 68,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "OM-1555",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.31,
    color: "Very Light Pink",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.72 x 3.33 x 2.20 mm",
    tablePercent: 53,
    depthPercent: 66,
    featured: false,
  },
  {
    sku: "OM-1556",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 1.03,
    color: "W-X",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.55 x 6.35 x 3.71 mm",
    tablePercent: 66,
    depthPercent: 58.5,
    featured: false,
  },
  {
    sku: "OM-1557",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1.01,
    color: "Y-Z",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.23 x 5.21 x 3.62 mm",
    tablePercent: 67,
    depthPercent: 69.4,
    featured: false,
  },
  {
    sku: "OMV-712",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 1,
    color: "Fancy Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.87 x 4.91 x 3.49 mm",
    tablePercent: 56,
    depthPercent: 71.1,
    featured: false,
  },
  {
    sku: "OMV-719",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 3.06,
    color: "U-V",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "7.70 x 7.67 x 5.35 mm",
    tablePercent: 60,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "OMV-731",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "6.23 x 5.08 x 3.54 mm",
    tablePercent: 55,
    depthPercent: 69.8,
    featured: false,
  },
  {
    sku: "OMV-734",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 2,
    color: "Fancy Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "8.62 x 6.39 x 4.51 mm",
    tablePercent: 62,
    depthPercent: 70.6,
    featured: false,
  },
  {
    sku: "OMV-736",
    shape: "oval",
    shapeName: "Oval",
    shapeCode: "OV",
    origin: "natural",
    carat: 1.66,
    color: "Fancy Light Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "8.59 x 6.03 x 3.96 mm",
    tablePercent: 61,
    depthPercent: 65.8,
    featured: false,
  },
  {
    sku: "OMV-737",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 1.76,
    color: "Fancy Light Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "10.18 x 6.14 x 4.11 mm",
    tablePercent: 54,
    depthPercent: 66.9,
    featured: false,
  },
  {
    sku: "OM-KG-14",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.51,
    color: "Fancy Vivid Yellow",
    clarity: "VS1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.82 x 3.86 x 2.71 mm",
    tablePercent: 58,
    depthPercent: 70.1,
    featured: false,
  },
  {
    sku: "OM-KG-17",
    shape: "marquise",
    shapeName: "Marquise",
    shapeCode: "MQ",
    origin: "natural",
    carat: 0.66,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "8.20 x 4.14 x 2.63 mm",
    tablePercent: 55,
    depthPercent: 63.4,
    featured: false,
  },
  {
    sku: "OM-KG-21",
    shape: "pear",
    shapeName: "Pear",
    shapeCode: "PS",
    origin: "natural",
    carat: 0.5,
    color: "Fancy Yellow",
    clarity: "SI1",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "Medium",
    lab: "GIA",
    measurements: "6.75 x 3.93 x 2.61 mm",
    tablePercent: 58,
    depthPercent: 66.3,
    featured: false,
  },
  {
    sku: "OM-KG-23",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.65,
    color: "Fancy Intense Yellow",
    clarity: "SI1",
    polish: "Excellent",
    symmetry: "Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "5.37 x 4.15 x 3.06 mm",
    tablePercent: 61,
    depthPercent: 73.9,
    featured: false,
  },
  {
    sku: "OM-KG-28",
    shape: "radiant",
    shapeName: "Radiant",
    shapeCode: "RA",
    origin: "natural",
    carat: 0.51,
    color: "Fancy Intense Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "GIA",
    measurements: "4.85 x 3.87 x 2.69 mm",
    tablePercent: 68,
    depthPercent: 69.6,
    featured: false,
  },
  {
    sku: "KC-4479",
    shape: "heart",
    shapeName: "Heart",
    shapeCode: "HT",
    origin: "natural",
    carat: 1.51,
    color: "Fancy Intense Yellow",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.23 x 7.17 x 4.19 mm",
    tablePercent: 51,
    depthPercent: 58.5,
    featured: false,
  },
  {
    sku: "KC-4582",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1.32,
    color: "Fancy Brownish Yellow",
    clarity: "VS1",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "6.07 x 5.78 x 3.98 mm",
    tablePercent: 62,
    depthPercent: 68.9,
    featured: false,
  },
  {
    sku: "OK-1",
    shape: "cushion",
    shapeName: "Cushion",
    shapeCode: "CU",
    origin: "natural",
    carat: 1,
    color: "Y-Z",
    clarity: "VS2",
    polish: "Excellent",
    symmetry: "Very Good",
    fluorescence: "Faint",
    lab: "GIA",
    measurements: "5.78 x 5.14 x 3.53 mm",
    tablePercent: 64,
    depthPercent: 68.7,
    featured: false,
  },
];
