import "server-only";
import data from "@/data/jewelry.json";
import { toSummary, type Jewel, type JewelSummary } from "./jewelry";

/**
 * Finished jewelry stock, generated by `npm run jewelry:scrape` from the
 * supplier's storefront. Don't edit src/data/jewelry.json by hand — re-run the
 * script; SKUs are kept stable in scripts/data/jewelry-skus.json.
 *
 * Server-only: the file carries full written specifications and supplier
 * pricing. Pages hand the browser `JewelSummary` objects instead.
 */
export const ALL_JEWELRY = data as Jewel[];

/** For the catalogue: cards and the drawer use the cover and hover shots only. */
export const JEWELRY_SUMMARIES: JewelSummary[] = ALL_JEWELRY.map((j) => ({
  ...toSummary(j),
  images: j.images.slice(0, 2),
}));

export function findJewel(sku: string): Jewel | undefined {
  return ALL_JEWELRY.find((j) => j.sku === sku);
}
