import type { Stone } from "./stones";

/**
 * Real lab-grown round stock, supplied by the trade desk (Surat). Report
 * numbers are intentionally left out of this file — they ship in the client
 * bundle like everything else here, and the site's design promises those only
 * "on enquiry", not to every visitor.
 */
export const REAL_ROUND_LAB_STONES: Stone[] = [
  {
    sku: "TP-280626-3329",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.5,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.22 x 7.24 x 4.53 mm",
    tablePercent: 59,
    depthPercent: 62.6,
    featured: false,
  },
  {
    sku: "TP-290526-3280",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.5,
    color: "E",
    clarity: "VS1",
    cut: "Very Good",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.26 x 7.29 x 4.62 mm",
    tablePercent: 55,
    depthPercent: 63.6,
    featured: false,
  },
  {
    sku: "TP-160625-1460",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.41,
    color: "F",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.23 x 7.25 x 4.41 mm",
    tablePercent: 59,
    depthPercent: 60.9,
    featured: false,
  },
  {
    sku: "TP-190425-1260",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.34,
    color: "E",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.02 x 7.04 x 4.37 mm",
    tablePercent: 59,
    depthPercent: 62.2,
    featured: false,
  },
  {
    sku: "TP-191225-2918",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.31,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "7.07 x 7.11 x 4.27 mm",
    tablePercent: 58,
    depthPercent: 60.3,
    featured: false,
  },
  {
    sku: "TP-190425-1258",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.3,
    color: "E",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.98 x 7 x 4.32 mm",
    tablePercent: 58,
    depthPercent: 61.8,
    featured: false,
  },
  {
    sku: "TP-130326-3154",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.23,
    color: "E",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.84 x 6.86 x 4.24 mm",
    tablePercent: 57,
    depthPercent: 61.9,
    featured: false,
  },
  {
    sku: "TP-191225-2919",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.22,
    color: "E",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.92 x 6.95 x 4.13 mm",
    tablePercent: 59,
    depthPercent: 59.6,
    featured: false,
  },
  {
    sku: "TP-060126-2953",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.2,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.76 x 6.78 x 4.24 mm",
    tablePercent: 58,
    depthPercent: 62.7,
    featured: false,
  },
  {
    sku: "TP-310126-3066",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.2,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.77 x 6.8 x 4.2 mm",
    tablePercent: 59,
    depthPercent: 61.9,
    featured: false,
  },
  {
    sku: "TP-150826-3372",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.09,
    color: "E",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.65 x 6.69 x 4.03 mm",
    tablePercent: 59,
    depthPercent: 60.4,
    featured: false,
  },
  {
    sku: "TP-150826-3370",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.05,
    color: "E",
    clarity: "VVS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.56 x 6.59 x 3.97 mm",
    tablePercent: 58,
    depthPercent: 60.5,
    featured: false,
  },
  {
    sku: "TP-150826-3371",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.01,
    color: "E",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.5 x 6.52 x 3.92 mm",
    tablePercent: 58,
    depthPercent: 60.2,
    featured: false,
  },
  {
    sku: "TP-030926-3381",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1.01,
    color: "F",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.41 x 6.44 x 3.99 mm",
    tablePercent: 57,
    depthPercent: 62.2,
    featured: false,
  },
  {
    sku: "TP-030926-3384",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1,
    color: "E",
    clarity: "VS2",
    cut: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.31 x 6.35 x 4.01 mm",
    tablePercent: 56,
    depthPercent: 63.4,
    featured: false,
  },
  {
    sku: "TP-180526-3260",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 1,
    color: "D",
    clarity: "VS1",
    cut: "Very Good",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.45 x 6.48 x 3.83 mm",
    tablePercent: 59,
    depthPercent: 59.2,
    featured: false,
  },
  {
    sku: "TP-100425-1221",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.96,
    color: "D",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.38 x 6.41 x 3.85 mm",
    tablePercent: 59,
    depthPercent: 60.3,
    featured: false,
  },
  {
    sku: "TP-160625-1473",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.91,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.18 x 6.2 x 3.84 mm",
    tablePercent: 58,
    depthPercent: 62,
    featured: false,
  },
  {
    sku: "TP-010425-1156",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.9,
    color: "D",
    clarity: "VVS2",
    cut: "Ideal",
    polish: "Excellent",
    symmetry: "Excellent",
    fluorescence: "None",
    lab: "IGI",
    measurements: "6.23 x 6.25 x 3.75 mm",
    tablePercent: 59,
    depthPercent: 60.1,
    featured: false,
  },
  {
    sku: "TP-220725-1984",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.79,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.83 x 5.89 x 3.67 mm",
    tablePercent: 61,
    depthPercent: 62.6,
    featured: false,
  },
  {
    sku: "TP-220725-1988",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.74,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.73 x 5.76 x 3.59 mm",
    tablePercent: 58,
    depthPercent: 62.5,
    featured: false,
  },
  {
    sku: "TP-191225-2923",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.74,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.79 x 5.84 x 3.56 mm",
    tablePercent: 63,
    depthPercent: 61.2,
    featured: false,
  },
  {
    sku: "TP-191225-2926",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.55,
    color: "D",
    clarity: "VS1",
    cut: "Excellent",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.18 x 5.21 x 3.28 mm",
    tablePercent: 61,
    depthPercent: 63.1,
    featured: false,
  },
  {
    sku: "TP-220725-1991",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.52,
    color: "D",
    clarity: "VS1",
    cut: "Very Good",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.03 x 5.07 x 3.28 mm",
    tablePercent: 60,
    depthPercent: 64.9,
    featured: false,
  },
  {
    sku: "TP-220725-1993",
    shape: "round",
    shapeName: "Round",
    shapeCode: "RD",
    origin: "lab",
    carat: 0.51,
    color: "D",
    clarity: "VS1",
    cut: "Ideal",
    polish: "Very Good",
    symmetry: "Very Good",
    fluorescence: "None",
    lab: "IGI",
    measurements: "5.1 x 5.14 x 3.18 mm",
    tablePercent: 59,
    depthPercent: 62.1,
    featured: false,
  },
];
