import type { ShapeSlug } from "@/lib/shapes";

/**
 * Shape names per language, for the seasonal pages only.
 *
 * `SHAPES` carries the English trade names the rest of the site runs on; this
 * is the shop-window wording a buyer reading in their own language expects.
 * Where a market has settled on the English term — Asscher, Radiant — that term
 * is kept rather than invented afresh.
 */

export type SeasonalLang = "en" | "fr" | "de" | "it" | "es" | "ja" | "ko" | "zh";

export const SHAPE_NAMES: Record<SeasonalLang, Record<ShapeSlug, string>> = {
  en: {
    round: "Round",
    princess: "Princess",
    cushion: "Cushion",
    emerald: "Emerald",
    oval: "Oval",
    pear: "Pear",
    marquise: "Marquise",
    radiant: "Radiant",
    asscher: "Asscher",
    heart: "Heart",
    trillion: "Trillion",
    hexagon: "Hexagon",
  },
  fr: {
    round: "Rond",
    princess: "Princesse",
    cushion: "Coussin",
    emerald: "Émeraude",
    oval: "Ovale",
    pear: "Poire",
    marquise: "Marquise",
    radiant: "Radiant",
    asscher: "Asscher",
    heart: "Cœur",
    trillion: "Trillion",
    hexagon: "Hexagone",
  },
  de: {
    round: "Rund",
    princess: "Prinzess",
    cushion: "Kissen",
    emerald: "Smaragd",
    oval: "Oval",
    pear: "Tropfen",
    marquise: "Marquise",
    radiant: "Radiant",
    asscher: "Asscher",
    heart: "Herz",
    trillion: "Trillant",
    hexagon: "Hexagon",
  },
  it: {
    round: "Rotondo",
    princess: "Princess",
    cushion: "Cuscino",
    emerald: "Smeraldo",
    oval: "Ovale",
    pear: "Goccia",
    marquise: "Marquise",
    radiant: "Radiant",
    asscher: "Asscher",
    heart: "Cuore",
    trillion: "Trillion",
    hexagon: "Esagono",
  },
  es: {
    round: "Redondo",
    princess: "Princesa",
    cushion: "Cojín",
    emerald: "Esmeralda",
    oval: "Ovalado",
    pear: "Pera",
    marquise: "Marquesa",
    radiant: "Radiante",
    asscher: "Asscher",
    heart: "Corazón",
    trillion: "Trillón",
    hexagon: "Hexágono",
  },
  ja: {
    round: "ラウンド",
    princess: "プリンセス",
    cushion: "クッション",
    emerald: "エメラルド",
    oval: "オーバル",
    pear: "ペアシェイプ",
    marquise: "マーキス",
    radiant: "ラディアント",
    asscher: "アッシャー",
    heart: "ハート",
    trillion: "トリリアント",
    hexagon: "ヘキサゴン",
  },
  ko: {
    round: "라운드",
    princess: "프린세스",
    cushion: "쿠션",
    emerald: "에메랄드",
    oval: "오벌",
    pear: "페어",
    marquise: "마퀴즈",
    radiant: "래디언트",
    asscher: "애셔",
    heart: "하트",
    trillion: "트릴리언",
    hexagon: "헥사곤",
  },
  zh: {
    round: "圆形",
    princess: "公主方形",
    cushion: "垫形",
    emerald: "祖母绿形",
    oval: "椭圆形",
    pear: "梨形",
    marquise: "马眼形",
    radiant: "雷迪恩形",
    asscher: "阿斯切形",
    heart: "心形",
    trillion: "三角形",
    hexagon: "六角形",
  },
};
